# Generated by Django 3.0.7 on 2020-07-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingcart',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
